Create a Python script answering the problems below and submit here (not to Github). Also, call me over to see demo if you finish before the lab is over.

1. Import the numpy package with the alias np

2. Create a vector of zeros of size 10 but the fifth value which is 1 

3. Create a 3 X 3 array of any values. Add a column of ones to the end

4. Create a vector with values ranging from 10 to 49 

5. Reverse the above vector (first element becomes last)

6. Create a 4x4 matrix with values ranging from 0 to 15 

7. Create a 3x3x3 array with random values 

8. Create a 10x10 array with random values and find the minimum and maximum values 

9. Create a random vector of size 30 and find the mean value 

10. What does NaN mean? Submit in a comment

11. Write a function that takes 1D array and negates all elements which are between 3 and 8, in place. Demo it with an array of your choosing

 

In [8]:
import numpy as np

vec1 = np.zeros(10)
vec1[4] = 1
vec1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [31]:
np.append(np.zeros((3, 3)), np.ones((3, 1)), axis=1)

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [40]:
np.reshape(np.arange(16), (4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.random.rand(3, 3, 3)

array([[[ 0.34621709,  0.5209991 ,  0.2841338 ],
        [ 0.28404878,  0.06575532,  0.2055935 ],
        [ 0.94366995,  0.07652583,  0.79696885]],

       [[ 0.86062183,  0.90825459,  0.25574024],
        [ 0.32889585,  0.36056981,  0.63242737],
        [ 0.34616365,  0.31014825,  0.63669665]],

       [[ 0.17135608,  0.4980131 ,  0.17097521],
        [ 0.34228321,  0.09249335,  0.08996997],
        [ 0.44345039,  0.35002776,  0.42410184]]])

In [88]:
vec2 = np.random.rand(10, 10)

In [80]:
vec2.min()

0.016031936555687132

In [89]:
vec2.max()

0.99311795516207224

In [102]:
np.random.rand(30).mean()

0.55765877175500667

In [ ]:
# NaN means Not a Number

In [114]:
def invert_three_to_eight(array):
    array[(array > 3) & (array < 8)] *= -1
    
demo_array = np.around(np.random.rand(30) * 12, decimals=2)
invert_three_to_eight(demo_array)
demo_array

array([ -6.67,  -4.86,   3.  ,   1.43,   2.91,  -5.21,   2.59,  10.62,
        -4.4 ,   9.39,   0.58,  -4.22,  -7.37,   2.24,   0.74,   9.41,
        -6.11,  10.71,  11.68,  -3.47,   1.1 ,  -7.02,  -3.17,  -4.85,
        11.3 ,   8.9 ,  11.44,  -4.07,  -6.96,   2.76])